#!/usr/bin/env python3
"""Extract the Morgan Hand Mill (MHM) manual PDFs to plain text.

The MHM manual is a copyrighted document (Tom Morgan / Morgan Hand Mill). We do
NOT redistribute it: the raw PDFs and their extracted text live under
``data/raw/mhm/`` which is gitignored (mirroring how the RMA archive is handled).
Only the *derived, attributed* knowledge base is committed:

  - ``data/kb/mhm_kb.json`` — a curated, factual KB (machine layout, the taper
    "setting" model, the A-K hold-down/mill-stop rule, per-chapter summaries).
    Authored from the extracted text; not machine-generated by this script.
  - ``docs/MHM.md`` — a human-readable "how to use the Hand Mill" reference.

This script only performs the reproducible *extraction* step: unzip the manual
into ``data/raw/mhm/pdf/`` yourself, then run this to (re)generate the per-chapter
text under ``data/raw/mhm/txt/`` and a ``chapters_index.json`` manifest. Curation
of ``mhm_kb.json`` is a separate, human/LLM step on top of that text.

Requires the ``pdftotext`` CLI (poppler-utils): ``brew install poppler`` or
``apt-get install poppler-utils``.

Usage:
    python3 scripts/build_mhm_kb.py
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

RAW = Path(__file__).resolve().parent.parent / "data" / "raw" / "mhm"
PDF_DIR = RAW / "pdf"
TXT_DIR = RAW / "txt"


def require_pdftotext() -> None:
    if shutil.which("pdftotext") is None:
        sys.exit(
            "pdftotext not found. Install poppler-utils "
            "(`brew install poppler` / `apt-get install poppler-utils`)."
        )


def pdf_page_count(pdf: Path) -> int | None:
    """Page count via `pdfinfo`, if available; else None."""
    if shutil.which("pdfinfo") is None:
        return None
    out = subprocess.run(
        ["pdfinfo", str(pdf)], capture_output=True, text=True, check=False
    ).stdout
    for line in out.splitlines():
        if line.startswith("Pages:"):
            return int(line.split()[1])
    return None


def main() -> None:
    require_pdftotext()
    if not PDF_DIR.is_dir():
        sys.exit(f"missing {PDF_DIR} — unzip the MHM manual PDFs there first")

    TXT_DIR.mkdir(parents=True, exist_ok=True)
    index = []
    for pdf in sorted(PDF_DIR.glob("*.pdf")):
        stem = pdf.stem
        txt = TXT_DIR / f"{stem}.txt"
        # -layout keeps the station/setting tables aligned in the text.
        subprocess.run(
            ["pdftotext", "-layout", str(pdf), str(txt)], check=True
        )
        chars = len(txt.read_text(errors="replace").split())
        index.append(
            {
                "chapter_file": pdf.name,
                "text_file": txt.name,
                "pages": pdf_page_count(pdf),
                "word_count": chars,
            }
        )
        print(f"  extracted {pdf.name} -> {txt.name}")

    (RAW / "chapters_index.json").write_text(json.dumps(index, indent=2) + "\n")
    print(f"\n{len(index)} chapters extracted to {TXT_DIR}")
    print("Curate data/kb/mhm_kb.json + docs/MHM.md from these (human/LLM step).")


if __name__ == "__main__":
    main()
